src/Fideni/CoreBundle/Entity/Subscription.php
<?php

namespace Fideni\CoreBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Fideni\UserBundle\Entity\User;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Subscription
 *
 * @ORM\Table(name="subscription")
 * @ORM\Entity(repositoryClass="Fideni\CoreBundle\Repository\SubscriptionRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Subscription
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    
    /**
     * @ORM\ManyToOne(targetEntity="Fideni\UserBundle\Entity\User")
     * @Assert\NotBlank()
     */
    protected $user;


    /**
     * @ORM\ManyToOne(targetEntity="Fideni\CoreBundle\Entity\Campaign", cascade={"persist"})
     * @Assert\NotBlank()
     */
    protected $campaign;

    /**
     * @ORM\OneToMany(targetEntity="Fideni\CoreBundle\Entity\Share", mappedBy="subscription", cascade={"persist"})
     */
    protected $shares;


    /**
     * @ORM\Column(name="nb_shares", type="integer", nullable=false)
     */
    protected $nbShares;

    /**
     * @ORM\PrePersist()
     */
    public function createShares()
    {
        $nbShares = $this->nbShares;
        while ($nbShares > 0 ){
            $share = new Share();
            $share->setNominalValue($this->getSharePrice());
            $share->setSubscription($this);
            $this->addShare($share);
            --$nbShares;
        }
    }
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set user
     *
     * @param \Fideni\UserBundle\Entity\User $user
     * @return Subscription
     */
    public function setUser(\Fideni\UserBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \Fideni\UserBundle\Entity\User 
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @return mixed
     */
    public function getCampaign()
    {
        return $this->campaign;
    }

    /**
     * @param mixed $campaign
     * @return $this
     */
    public function setCampaign($campaign)
    {
        $this->campaign = $campaign;
        
        return $this;
    }
    
    
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->shares = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add share
     *
     * @param \Fideni\CoreBundle\Entity\Share $share
     * @return Subscription
     */
    public function addShare(\Fideni\CoreBundle\Entity\Share $share)
    {
        if($share instanceof Share){
            $this->shares[] = $share;
        }

        return $this;
    }

    /**
     * Remove share
     *
     * @param \Fideni\CoreBundle\Entity\Share $share
     */
    public function removeShare(\Fideni\CoreBundle\Entity\Share $share)
    {
        $this->shares->removeElement($share);
    }

    /**
     * Get shares
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getShares()
    {
        return $this->shares;
    }

    /**
     * @return string
     */
    public function getPartner(){

        if($this->getUser() instanceof  User){
            return $this->getUser()->getName(). ' ' .$this->getUser()->getSurname();
        }

        return '';
    }

    public function getShareNumber()
    {

        return $this->shares->count();
    }

    public function getSharePrice()
    {

        if($this->getCampaign() instanceof  Campaign){
            return $this->getCampaign()->getSharePrice();
        }

        return 'NC';
    }

    /**
     * @return int|string
     */
    public function __toString()
    {
        if($this->campaign instanceof  Campaign){
            return 'Campagne ' . $this->campaign->__toString();
        }
        return ''. $this->id;
    }

    /**
     * @return mixed
     */
    public function getNbShares()
    {
        return $this->nbShares;
    }

    /**
     * @param mixed $nbShares
     * @return $this
     */
    public function setNbShares($nbShares)
    {
        $this->nbShares = $nbShares;
        
        return $this;
    }
    
    
}

src/Fideni/CoreBundle/Controller/DefaultController.php
<?php

namespace Fideni\CoreBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class DefaultController extends Controller
{
    public function indexAction()
    {
        return $this->render('FideniCoreBundle:default:base_layout.html.twig');
    }
}

src/Fideni/CoreBundle/Resources/views/default/base_layout.html.twig
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html ng-app="myApp" ng-controller="MainController" >
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Fideni</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="icon" type="image/x-icon" href="{{ '/bundles/fidenicore/img/logo.jpeg'|imagine_filter('my_favicon') }}" />

  {% block stylesheet %}
    <link rel="stylesheet" href="{{ asset('bundles/easyadmin/stylesheet/bootstrap.min.css')}}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('bundles/fidenicore/css/AdminLTE.min.css')}}">
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
    <link rel="stylesheet" href="{{ asset('bundles/fidenicore/css/skins/skin-blue.min.css')}}">
    <link rel="stylesheet" href="{{ asset('bundles/fidenicore/css/front_stylesheet.css') }}">

    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  {% endblock %}
</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
{% block body %}
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  {% block header %}
  {% include('@FideniCore/default/header.html.twig') %}
  <!-- Left side column. contains the logo and sidebar -->
  {% include('@FideniCore/default/sidebar.html.twig') %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Fideni
        <small> makes future better</small>
      </h1>
    </section>
    {% endblock %}
    <!-- Main content -->
    <section class="content content_block">
      {% block content %}

        <!-- Your Page Content Here -->
        {% include('@FideniCore/default/stats_boxes.html.twig') %}
        {% include '@FideniCore/default/users_listing.html.twig' %}
      {% endblock %}
    </section>

    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  {% include('@FideniCore/default/footer.html.twig') %}

  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->
{% block javascripts %}
  <!-- jQuery 2.2.3 -->
  <script src="{{ asset('bundles/easyadmin/javascript/jquery.min.js') }}"></script>
  <!-- Bootstrap 3.3.6 -->
  <script src="{{ asset('bundles/easyadmin/javascript/bootstrap.min.js')}}"></script>
  <!-- AdminLTE App -->
  <script src="{{ asset('bundles/fidenicore/js/app.min.js') }}"></script>
  <script src="{{ asset('bundles/fidenicore/js/Angular/angular.min.js') }}" type="text/javascript"></script>
  <script src="{{ asset('bundles/fidenicore/js/Angular/app.js') }}"></script>
  <script src="{{ asset('bundles/fidenicore/js/Angular/Constants/api-url.js') }}"></script>
  <script src="{{ asset('bundles/fidenicore/js/Angular/Controller/main-controller.js') }}"></script>
  <script src="{{ asset('bundles/fidenicore/js/Angular/Services/httpService.js') }}"></script>
{% endblock %}

<!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. Slimscroll is required when using the
     fixed layout. -->
{% endblock %}
</body>
</html>

src/Fideni/CoreBundle/Resources/views/default/cession.html.twig
{% extends '@EasyAdmin/default/new.html.twig' %}
{% block entity_form %}
    {{ form_start(form, { 'attr': { 'class': 'form-horonzital' }}) }}
    <div class="row">
        <div class="col-xs-12 form-group">
            {{ form_label(form.sellingPrice, '', { 'label_attr': { 'class': 'col-sm-2 control-label text-right'} }) }}
            {{ form_errors(form.sellingPrice) }}
            <div class="col-sm-10"> {{ form_widget(form.sellingPrice, { 'attr': { 'class': 'form-control' } }) }}</div>
        </div>
        <div class="col-xs-12 form-group">
            {{ form_label(form.seller, '', { 'label_attr': { 'class': 'col-sm-2 ontrol-label text-right' } }) }}
            {{ form_errors(form.seller) }}
            <div class="col-sm-10"> {{ form_widget(form.seller, { 'attr': { 'class': 'form-control', 'data-widget': 'select2' } }) }}</div>
        </div>
        <div class="col-xs-12 form-group">
            {{ form_label(form.buyer, '', { 'label_attr': { 'class': 'col-sm-2 ontrol-label text-right' } }) }}
            {{ form_errors(form.buyer) }}
            <div class="col-sm-10"> {{ form_widget(form.buyer, { 'attr': { 'class': 'form-control', 'data-widget': 'select2' } }) }}</div>
        </div>
        <div class="col-xs-12 form-group">
            {{ form_label(form.shares, '', { 'label_attr': { 'class': 'col-sm-2 ontrol-label text-right' } }) }}
            {{ form_errors(form.shares) }}
            <div class="col-sm-10"> {{ form_widget(form.shares, { 'attr': { 'class': 'form-control' } }) }}</div>
        </div>
    </div>
    {{ form_end(form) }}
{% endblock entity_form %}

src/Fideni/CoreBundle/Resources/views/default/footer.html.twig
<footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
        Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; {{ 'now'|date('Y') }} <a href="#">Fideni</a>.</strong> All rights reserved.
</footer>

src/Fideni/CoreBundle/Resources/views/default/header.html.twig
<!-- Main Header -->
<header class="main-header">

    <!-- Logo -->
    <a href="{{ path('fideni_core_homepage') }}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>F</b>P</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Acceuil</b></span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                {% if is_granted('ROLE_ADMIN') %}
                <li>
                    <a href="{{ url('easyadmin') }}">Administration</a>
                </li>
                {% endif %}
                <!-- User Account Menu -->
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        {% if app.user.photo is defined and app.user.photo is not empty %}
                            <img src="{{ vich_uploader_asset(app.user, 'photoFile')|imagine_filter('my_thumb') }}" class="user-image" alt="User Image">
                        {% else %}
                            <img src="{{ asset('bundles/fidenicore/img/user5-128x128.jpg')|imagine_filter('my_thumb') }}" class="user-image">
                        {% endif %}
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">{{ app.user.name }} {{ app.user.surname }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            {% if app.user.photo is defined and app.user.photo is not empty %}
                                <img src="{{ vich_uploader_asset(app.user, 'photoFile')|imagine_filter('my_thumb') }}" class="img-circle" alt="User Image">
                            {% else %}
                                <img src="{{ asset('bundles/fidenicore/img/user5-128x128.jpg')|imagine_filter('my_thumb') }}" class="img-circle">
                            {% endif %}

                            <p>
                                {{ app.user.name }} {{ app.user.surname }}
                                <small>Member since {{ app.user.createdAt|date('dmY')}}</small>
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <li class="user-body">

                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{{ path('fideni_user_profile_show') }}" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a href="{{ path('fos_user_security_logout') }}" class="btn btn-default btn-flat">Déconnexion</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

src/Fideni/CoreBundle/Resources/views/default/sidebar.html.twig
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                {% if app.user.photo is defined and app.user.photo is not empty %}
                <img src="{{ vich_uploader_asset(app.user, 'photoFile')|imagine_filter('my_thumb') }}" class="img-circle" alt="User Image">
                {% else %}
                    <img src="{{ asset('bundles/fidenicore/img/user5-128x128.jpg')|imagine_filter('my_thumb') }}" class="img-circle">
                {% endif %}
            </div>
            <div class="pull-left info">
                <p>{{ app.user.name }} {{ app.user.surname }}</p>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <ul class="sidebar-menu">
            <li class="header"></li>
            <!-- Optionally, you can add icons to the links -->
            <li class="active"><a href="{{ url('fideni_user_profile_show') }}"><i class="fa fa-link"></i> <span>Mon profile</span></a></li>
            <li><a href="#" ng-click="showGlobalInfo()"><i class="fa fa-link"></i> <span>Informations générales</span></a></li>
            <li><a href="#"><i class="fa fa-link"></i> <span>Projets financés</span></a></li>
            <li><a href="#"><i class="fa fa-link"></i> <span>Status</span></a></li>
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>

src/Fideni/CoreBundle/Resources/views/default/stats_boxes.html.twig
<div class="row">
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>{% verbatim %}{{ fideni.numberOfPartners}} {% endverbatim %}</h3>

                <p>Actionnaires</p>
            </div>
            {#<div class="icon">#}
                {#<i class="ion ion-"></i>#}
                {#<i class="ion ion-bag"></i>#}
            {#</div>#}
            <a na class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-green">
            <div class="inner">
                <h3>{% verbatim %}{{ fideni.numberOfProjets }}{% endverbatim %}</h3>

                <p>Projets financés</p>
            </div>
            {#<div class="icon">#}
                {#<i class="ion ion-stats-bars"></i>#}
            {#</div>#}
            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-yellow">
            <div class="inner">
                <h3>{% verbatim %}{{ fideni.assetInBank }}{% endverbatim %}</h3>

                <p>Argent en banque</p>
            </div>
            {#<div class="icon">#}
                {#<i class="ion ion-person-add"></i>#}
            {#</div>#}
            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-red">
            <div class="inner">
                <h3>{% verbatim %}{{ fideni.sharePrice }} CFA {% endverbatim %}</h3>

                <p>Cours de l'action</p>
            </div>
            {#<div class="icon">#}
                {#<i class="ion ion-pie-graph"></i>#}
            {#</div>#}
            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
</div>
<div class="row" ng-hide="hideStats">
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-green">
            <div class="inner">
                <h3>{% verbatim %}{{ fideni.capital}} CFA {% endverbatim %}</h3>

                <p>Capitale</p>
            </div>
            {#<div class="icon">#}
                {#<i class="ion ion-"></i>#}
                {#<i class="ion ion-bag"></i>#}
            {#</div>#}
            <a na class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>{% verbatim %}{{ fideni.investedAmount }}{% endverbatim %}</h3>

                <p>Capital</p>
            </div>
            {#<div class="icon">#}
                {#<i class="ion ion-stats-bars"></i>#}
            {#</div>#}
            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-red">
            <div class="inner">
                <h3>{% verbatim %}{{ fideni.numberOfShares }}{% endverbatim %}</h3>

                <p>Nombre total d'actions</p>
            </div>
            {#<div class="icon">#}
                {#<i class="ion ion-person-add"></i>#}
            {#</div>#}
            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-yellow">
            <div class="inner">
                <h3>{% verbatim %}{{ fideni.numberOfSoldShares }}{% endverbatim %}</h3>

                <p>Nombre d'actions détenues</p>
            </div>
            {#<div class="icon">#}
                {#<i class="ion ion-pie-graph"></i>#}
            {#</div>#}
            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
</div>
<script>

</script>

src/Fideni/CoreBundle/Resources/views/default/users_listing.html.twig
<h1>Liste des associés</h1>
<div class="box-body no-padding container">
    <ul class="users-list2 list-inline row">
        <li ng-repeat="partner in partners" class="list-inline col-md-2">
            <img ng-if="patner.photo != null" src="{{ user_image_resize_dir }}{% verbatim %}{{partner.photo}}{%endverbatim%}" alt="User Image">
            <img ng-if="patner.photo == null" src="{{ asset('bundles/fidenicore/img/user5-128x128.jpg')|imagine_filter('my_thumb') }}" alt="User Image">
            <a class="users-list-name" href="/profile/{% verbatim %}{{partner.id}}{%endverbatim%}">{% verbatim %}{{partner.name}} {{partner.surname}}{%endverbatim%}</a>
            <span class="users-list-date">Today</span>
        </li>
    </ul>
</div>